[package]
name = "midi-staff-trainer"
version = "0.4.5"
edition = "2024"
description = "Interactive MIDI keyboard to musical staff trainer"
license = "BSD-3-Clause"

[dependencies]
eframe = "0.36"
egui = "0.36"
midir = "0.10"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "symbols"
